version: '3'
services:
  db:
    image: mysql:5.7
    container_name: dw_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deepwork
      MYSQL_USER: django
      MYSQL_PASSWORD: django123
    ports:
      - "13306:3306"
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "django", "-pdjango123", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dw_django
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: deepwork
      MYSQL_USER: django
      MYSQL_PASSWORD: django123
      MYSQL_HOST: db
      MYSQL_PORT: 3306
